# 目录结构
## Jekyll 读取文件的路径
source:      .
## Jekyll 写入文件的路径
destination: ./_site
plugins_dir:     ./_plugins
layouts_dir:     ./_layouts
data_dir: ./_data
collections: null

# 阅读处理
## 开启自定义插件
safe: false
## 转换时排除某些文件、文件夹
exclude: [README.md, TODO.md, LICENSE, node_modules, Makefile, Gulpfile.js, package.json]
## 设置文件的编码，仅 Ruby 1.9 以上可用。2.0.0　版本以后默认值为 utf-8，之前版本默认值为 nil，使用 Ruby 默认的 ASCII-8BIT
encoding: 'utf-8'
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# 转换
highlighter: pygments
markdown: redcarpet
excerpt_separator: <!-- more -->

# 服务器选项
detach:  false
port:    4000
host:    127.0.0.1
## does not include hostname
baseurl: "" 

title: Novaline的日记
email: novaline@qq.com

# Markdown 处理器
redcarpet:
  extensions: [autolink, fenced_code_blocks, tables, highlight, strikethrough]

# 输出
permalink: /post/:title
paginate: 20
paginate_path: "/page/:num"
## 设置时区, Ruby 用它来处理日期和时间。
timezone: 'Asia/Shanghai'

gems: [jekyll-paginate]

# rss配置
name: Novaline的日记
description: ''
url: http://mrdulin.github.io/index.html

# 头信息默认值
defaults:
  -
    scope:
      path: '' #空的字符串代表项目中所有的文件
      type: 'posts' #posts类型的文件使用post布局
    values: 
      layout: 'post'