# Site settings
timezone: 'Asia/Shanghai'
baseurl: /mrdulin.github.io
safe: false
title: Novaline的日记
email: novaline@qq.com
gems: []
encoding: 'utf-8'
excerpt_separator: <!-- more -->

highlighter: pygments
markdown: redcarpet

redcarpet:
  extensions: [autolink, fenced_code_blocks, tables, highlight, strikethrough]

exclude: [README.md, TODO.md, LICENSE, node_modules, Makefile, Gulpfile.js, package.json]


permalink: /post/:title

paginate: 20
paginate_path: "/page/:num"

# rss settings
name: Novaline的日记
description: ''
url: http://mrdulin.github.io/index.html
